[package]
name = "seichi-ranking-bff"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.0.1", features = ["rustls"] }
anyhow = "1.0.56"
async-lock = "2.5.0"
async-trait = "0.1.53"
chrono = "0.4.19"
envy = "0.4.2"
fern = { version = "0.6.0", features = ["colored"] }
log = "0.4.16"
once_cell = "1.10.0"
qstring = "0.7.2"
rustls = "0.20.4"
rustls-pemfile = "1.0.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
strum = { version = "0.24.0", features = ["derive"] }
tokio = { version = "1.17.0", features = ["macros"] }
uuid = { version = "0.8.2", features = ["serde"] }
