[package]
name = "seichi-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4", features = ["rustls"] }
rustls = "0.20"
rustls-pemfile = "0.3"
once_cell = "1"
fern = { version = "0.6", features = ["colored"] }
log = "0.4"
chrono = "0.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1"
qstring = "0.7"